name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: stiantha/stiantha.github.io # Specify your GitHub Pages repository
          path: portfolio # Specify the folder path

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies and Build
        run: |
          # Replace these commands with your actual build commands
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          mv portfolio/* ./ # Move contents of "portfolio" to the root
        shell: bash
