- name: Deploy to GH Page
  uses: stiantha/github-pages-deploy-action@4.1.1
  with:
    branch: main  # Change this to your main branch
    folder: portfolio  # Update this to your build output folder
    single-commit: false
on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 16.15

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to GH Page
        uses: stiantha/github-pages-deploy-action@4.1.1
        with:
          branch: main
          folder: stiantha.github.io/portfolio
          single-commit: false